apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: gcr.io/flaskgkeuploader/frontend:latest
        ports:
        - containerPort: 3000
        # Environment variables section must be inside the container definition
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "./application_default_credentials.json"     
      imagePullSecrets:
        - name: gcr-json-key

