
apiVersion: v1
kind: Namespace
metadata:
  name: flask-frontend-ns

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-frontend-configmap
  namespace: flask-frontend-ns
data:
  REACT_APP_BACKEND_URL: " https://flask-backend-service.flask-backend-ns.svc.cluster.local"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend-deployment
  namespace: flask-frontend-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-frontend-app
  template:
    metadata:
      labels:
        app: flask-frontend-app
    spec:
      containers:
        - name: flask-frontend
          image: gcr.io/proven-sum-435500-p1/flask-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: flask-frontend-configmap
      imagePullSecrets:
        - name: gcr-json-key

---

apiVersion: v1
kind: Service
metadata:
  name: flask-frontend-service
  namespace: flask-frontend-ns
spec:
  type: LoadBalancer
  selector:
    app: flask-frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
